version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "3030:3030"
    env_file:
      - ./api/.env
    depends_on:
      - mssql

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - api

  mssql:
    build: ./mssql
    container_name: mssql
    environment:
      SA_PASSWORD: "300304Cuba"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./mssql/helios.bak:/var/opt/mssql/backup/helios.bak

    command: /opt/mssql/bin/sqlservr

  ai:
    build: ./AI_Recommend
    ports:
      - "8000:8000"
    volumes:
      - ./AI_Recommend:/app
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    restart: always

volumes:
  mssql_data:
