version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: my_sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "300304Cuba"
      ACCEPT_EULA: "Y"
    volumes:
      - ./backup:/var/opt/mssql/backup
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
